# Cours 2 : Numpy algèbre et autres

(c) Fabrice Mulotti

In [2]:
import numpy as np

---
Exercice 1 : déclarer une matrice de 5 par 3 contenant des nombres de 0 à 14

In [3]:
mat = np.arange(0,15).reshape(5,3)

In [4]:
print(mat)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


----
Exercice 2 : Quelle est la valeur de l'élément en position (selon les indices python) 3,2 ?

In [6]:
mat[3,2]

11

---
Créer une matrice mat2 qui contient tous les éléments de la matrice mat multiplié par 2

In [41]:
mat2=mat*2

In [42]:
print(mat2)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]
 [24 26 28]]


---
Exercice 3 : Déclarer un matrice __mat3__ de dimension 5,3 ne contenant que des 1 

In [43]:
mat3=np.ones((5,3))

---
Exercice 4 : Additionner (en une ligne!) tous les éléments de cette matrice ?

In [44]:
np.sum(mat3)

15.0

---
Exercice 5 : Changer les dimensions de la matrice mat3 de 5,3 pour 3,5

In [45]:
mat3=mat3.reshape(3,5)

___
Exercice 6 : Déclarer une matrice mat4 de dimension 3,5 contenant que des chiffres 2, additionner les 2 matrices

In [46]:
mat4=np.full((3,5),2)

In [47]:
mat3+mat4

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

----
Exercice 7 : Déclarer un vecteur v de dimension 3,1 remplit de chiffres 2

In [48]:
v=np.full((3,1),2)

In [49]:
v

array([[2],
       [2],
       [2]])

---
Exercice 8 : Multiplier mat4 par v

In [50]:
np.dot(mat4,v)

ValueError: shapes (3,5) and (3,1) not aligned: 5 (dim 1) != 3 (dim 0)

Cela donne quoi ?

---
Exercice 8 : Ok, donnons nous un autre chance.<br>
Changer la dimension de la matrice 4 sous la forme 5,3.<br>
Essayer à nouveau la multiplication matricielle mat4 x v

In [51]:
mat4=mat4.reshape(5,3)

In [52]:
np.dot(mat4,v)

array([[12],
       [12],
       [12],
       [12],
       [12]])

---
Exercice 9 : Déclarer une matrice mat5 de dimension 3,3 avec la valeur 2 dans toutes les cellules

Multiplier et afficher mat5 par v

Multiplier et afficher v __transpose__ par mat5

In [53]:
mat5=np.full((3,3),2)

In [54]:
np.dot(mat5,v)

array([[12],
       [12],
       [12]])

In [55]:
np.dot(v.transpose(),mat5)

array([[12, 12, 12]])

---
Exercice 10 : Afficher la version transpose de notre matrice ___mat___.
Que constatez vous ?

In [56]:
mat.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [57]:
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])